services:
  subwave:
    image: subwave:latest
    pull_policy: never
    container_name: sub-wave
    restart: unless-stopped
    mem_limit: 16g
    environment:
      - TZ=Europe/Zurich
      - ADMIN_USER=admin
      - ADMIN_PASS=7D76mmHNJkFKDnhR
      - SITE_URL=https://subwave.vkugler.ch
      - ANALYZE_REQUEST_TIMEOUT_MS=600000
      - PUID=1035
      - PGID=100
    volumes:
      - /volume2/docker/subwave/state:/var/sub-wave
    ports:
      - "127.0.0.1:7700:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      navidrome:
        ipv4_address: 172.168.22.100

networks:
  navidrome:
    external: true
